### ISSUE TITLE
Wrong graph at "If you do not use Haskell at work, why not?"

### ISSUE THREAD

**Issue by sestrella** [tfausak/tfausak.github.io#149]
@tfausak great article about "2018 state of Haskell survey results"! I just found that the graph results on Question 12 mismatched with the question answers https://taylor.fausak.me/2018/11/18/2018-state-of-haskell-survey-results/#question-012

**Comment by tfausak** [comment]
The graph is correct, but it may be confusing for a couple reasons:

1. The labels on the graph (like "Company doesn't use") aren't the same as the answer choices (like "My company doesn't use Haskell"), which are listed in the table. The graph labels had to be shortened in order to show up. 

2. The graph excludes some of the least popular answer choices. This was done in order to keep everything readable.

**Comment by sestrella** [comment]
@tfausak thank you very much for the clarification, I'm closing this issue.
